Repository artiscruelty/CervejArte, pull requests merged in 2022-05, with the labels that each got.

#8 feat: footer
  assets/css/style.css
  index.html
Labels: good first issue

#9 feat: Arrumando readme
  README.md
  assets/css/style.css
  index.html
Labels: enhancement, good first issue

#10 fix: arrumando a estrutura do html
  assets/css/style.css
  index.html
Labels: bug

#11 feat: adicionando html da navbar
  index.html
Labels: documentation

#12 feat: adicionando link font awesome
  index.html
Labels: documentation

#13 Feature/feats
  assets/css/style.css
  index.html
Labels: enhancement

#14 feat:ajustandoFooter
  assets/css/style.css
  index.html
Labels: documentation, enhancement

#23 fix: arrumando conflitos
  index.html
Labels: bug, help wanted, good first issue

#24 Feature/navbar Add cards
  assets/src/Design sem nome.png
  assets/src/cerveja.png
  assets/src/cerveja2.png
  assets/src/cerveja3.jpg
  assets/src/cervejaartesanal-essa.jpg
  assets/src/cervejaartesanal.jpg
  assets/src/cervejaartesanal2.jpg
  index.html
Labels: documentation

#25 mais vendidos carrossel
  assets/css/style.css
  index.html
Labels: documentation, good first issue

#27 Feature/feats
  assets/css/images/banner-teste2.png
  assets/css/images/banner-teste3.png
  assets/css/images/banner-tste.png
  assets/src/Cards/CERVEJA TESTE.webp
  index.html
  screens/acompanharPedidos.html
  screens/cadastro.html
  screens/categorias.html
  screens/contaCliente.html
  screens/finalizarCompra.html
  screens/geladeira.html
  screens/login.html
  screens/produto.html
  styles/categoriasStyle.css
  styles/homeStyle.css
Labels: documentation, enhancement

#34 Feature/card
  assets/src/images/Cards/CERVEJA CARDS.jpg
  assets/src/images/Cards/CERVEJA CARDS2.jpg
  assets/src/images/Cards/CHOPP.png
  assets/src/images/Cards/cerveja-pi.jpg
  assets/src/images/Cards/cerveja.png
  assets/src/images/Cards/cerveja3.jpg
  assets/src/images/Cards/cervejaArtesanal.jpg
  assets/src/images/Cards/cervejaartesanal-essa.jpg
  assets/src/images/Cards/chopp-pi.jpg
  screens/home.html
  screens/produto.html
  styles/homeStyle.css
Labels: documentation, enhancement, good first issue
